### ISSUE TITLE
[FEATURE-REQ]Auto upgrade versions in Spring Cloud Azure to align with Spring Boot current version

### ISSUE THREAD

**Issue by Netyyyy** [Azure/spring-cloud-azure-tools#5]
### Context:
Currently Spring Cloud Azure upgrades Spring Boot dependencies manually, which takes a lot of time for repetitive work

### Goal:
Try to automate repeatable work as much as possible to reduce time spent each month

### Solutions
- Use Github Action to upgrade Spring Boot Dependencies
- Change scripts to support this action work well.

**Tasks:**
- [x] https://github.com/Azure/spring-cloud-azure-tools/pull/6
- [x] https://github.com/Azure/azure-sdk-for-java/pull/29293
- [x] https://github.com/Azure/azure-sdk-for-java/pull/29325
